//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lena.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public int Id { get; set; }
        public int FormId { get; set; }
        public string Name { get; set; }
        public string DataType { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Form Form { get; set; }
    }
}
